### ISSUE TITLE
when evaluating configs, check version before mvp_multivalue_args

### ISSUE THREAD

**Issue by karenetheridge** [rjbs/Config-MVP#9]
I added a new mvp_multivalue_arg option in a Dist::Zilla plugin.  When using it in dist.ini I do:

```
[PluginName]
:version = 0.002
option = foo
option = bar
```

However, when doing a build when the new version of the plugin is not installed, I get:
`multiple values given for property -include_sub in section PluginName at /Users/ether/.perlbrew/libs/21.6@std/lib/perl5/Config/MVP/Assembler.pm line 208.`

This is as not a clear an error as we'd get if the version was checked first: `Dist::Zilla::Plugin::PluginName version (0.001) does not match required version: 0.002`

Is it possible to check the version first before reading `PluginName->mvp_multivalue_args`?

**Comment by karenetheridge** [comment]
17:30 < kentnl> ether: yeah, makes sense, iirc, the parse validates mvp shit literally as its parsing the INI, but the :version bit happens afterwards in the finalize step
17:30 < kentnl> https://metacpan.org/source/RJBS/Config-MVP-2.200008/lib/Config/MVP/Section.pm#L192 
17:30 < dipsy> [ lib/Config/MVP/Section.pm - metacpan.org ] 
17:30 < kentnl> https://metacpan.org/source/RJBS/Dist-Zilla-5.031/lib/Dist/Zilla/MVP/Section.pm#L23   # by the time %payload exists, mvp has been assessed.
17:31 < dipsy> [ lib/Dist/Zilla/MVP/Section.pm - metacpan.org ] 
17:31  * kentnl wonders what happens if I do : sub mvp_multvalue_args { ":version" }
17:33 < kentnl> also, for fun: < sub mvp_aliases { ":version" => "_really_version" } > hue hue hue 
17:34 < kentnl> today, rjbs sets a goal of making a voodo doll that looks exactly like me,.

**Comment by rjbs** [comment]
So, this is a Dist-Zilla problem, not a Config-MVP problem.  But that's okay.

I have fixed it!  It's in rjbs/dist-zilla/check-version-earlier

I'll merge it once somebody writes a test for :version working at all. ;)

**Comment by karenetheridge** [comment]
done - https://github.com/rjbs/Dist-Zilla/pull/423

**Comment by rjbs** [comment]
this is now applied in git master
